[package]
name = "fast_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
xerune = { version = "0.1.0", path = "../", default-features = false }
fontdue = { version = "0.9.3", optional = true }
tiny-skia = { version = "0.12.0", optional = true }
ttf-parser = { version = "0.20", optional = true }
png = { version = "0.17", optional = true }
log = "0.4"
coarse-prof = { version = "0.2.6", optional = true }

[features]
default = ["std"]
std = ["xerune/std", "dep:tiny-skia", "dep:fontdue", "dep:ttf-parser", "dep:png"]
profile = ["dep:coarse-prof"]
